balibali_blog_backend_index:
    pattern:  /
    defaults: { _controller: Balibali\BlogBundle:Backend:index }

balibali_blog_backend_new:
    pattern:  /new
    defaults: { _controller: Balibali\BlogBundle:Backend:new }

balibali_blog_backend_create:
    pattern:  /create
    defaults: { _controller: Balibali\BlogBundle:Backend:create }
    requirements: { _method: post }

balibali_blog_backend_edit:
    pattern:  /edit/:id
    defaults: { _controller: Balibali\BlogBundle:Backend:edit }

balibali_blog_backend_update:
    pattern:  /update/:id
    defaults: { _controller: Balibali\BlogBundle:Backend:update }

balibali_blog_backend_delete:
    pattern:  /delete/:id
    defaults: { _controller: Balibali\BlogBundle:Backend:delete }
