balibali_blog_backend_index:
    pattern:  /
    defaults: { _controller: Balibali\BlogBundle:Backend:index }

balibali_blog_backend_new:
    pattern:  /posts/new
    defaults: { _controller: Balibali\BlogBundle:Backend:new }
    requirements: { _method: get }

balibali_blog_backend_create:
    pattern:  /posts
    defaults: { _controller: Balibali\BlogBundle:Backend:create }
    requirements: { _method: post }

balibali_blog_backend_edit:
    pattern:  /posts/:id/edit
    defaults: { _controller: Balibali\BlogBundle:Backend:edit }
    requirements: { _method: get }

balibali_blog_backend_update:
    pattern:  /posts/:id
    defaults: { _controller: Balibali\BlogBundle:Backend:update }
    requirements: { _method: put }

balibali_blog_backend_delete:
    pattern:  /posts/:id
    defaults: { _controller: Balibali\BlogBundle:Backend:delete }
    requirements: { _method: delete }
