balibali_blog_frontend_index:
    pattern:  /
    defaults: { _controller: Balibali\BlogBundle:Frontend:index }

balibali_blog_frontend_show:
    pattern:  /show/:id
    defaults: { _controller: Balibali\BlogBundle:Frontend:show }
